# Generated by Django 3.0.4 on 2020-05-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('result', models.IntegerField()),
                ('state', models.CharField(max_length=300)),
            ],
        ),
    ]
