# Generated by Django 3.0.4 on 2020-05-27 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200527_1521'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
