# Generated by Django 3.0.4 on 2020-05-27 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_eve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eve',
            old_name='name',
            new_name='number',
        ),
    ]
