# Generated by Django 3.0.4 on 2020-06-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20200527_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eye_thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_ear', models.DecimalField(decimal_places=3, max_digits=3)),
                ('close_ear', models.DecimalField(decimal_places=3, max_digits=3)),
                ('both_thread', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
        ),
    ]
