# Generated by Django 3.0.4 on 2020-06-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_eye_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eye_thread',
            name='both_thread',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='eye_thread',
            name='close_ear',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='eye_thread',
            name='open_ear',
            field=models.FloatField(),
        ),
    ]
