# Generated by Django 3.0.4 on 2020-06-01 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20200601_1620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eye_thread',
            new_name='Threashold',
        ),
        migrations.RenameField(
            model_name='threashold',
            old_name='both_thread',
            new_name='both_ear',
        ),
    ]
