# Generated by Django 3.0.4 on 2020-06-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_auto_20200601_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threashold',
            old_name='both_ear',
            new_name='ear_thresh',
        ),
    ]
