# Generated by Django 3.0.4 on 2020-06-02 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_auto_20200602_2200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Threashold',
            new_name='Threshold',
        ),
    ]
