# Generated by Django 3.0.4 on 2020-06-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_auto_20200602_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='threshold',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
