# Generated by Django 3.0.4 on 2020-06-02 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0009_threshold_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threshold',
            old_name='created',
            new_name='created_at',
        ),
    ]
