# Generated by Django 3.0.4 on 2020-06-15 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo', '0011_threshold_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threshold',
            old_name='student',
            new_name='user',
        ),
        migrations.AddField(
            model_name='eve',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
